image: python:3.7

pipelines:
  default:
    - step:
        name: Build
        caches:
          - pip
        script:
          - pip install -r pip-requirements.txt
          - pip install -r pip-requirements-dev.txt
    - step:
        name: Run tests
        script:
          - make test
